config/routes.rb
Rails.application.routes.draw do
  resources :user_feedbacks do
  collection do
      get 'last_feedback'
      post 'feedback'
    end
  end

end

app/models/user_feedback.rb
class UserFeedback < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_feedbacks_controller.rb
class UserFeedbacksController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_filter :authenticate_admin!
  before_action :set_user_feedback, only: [:show, :edit, :update, :destroy]
  # GET /user_feedbacks
  # GET /user_feedbacks.json
  def index
    @user_feedbacks = UserFeedback.all
  end

  # GET /user_feedbacks/1
  # GET /user_feedbacks/1.json
  def show
  end

  # GET /user_feedbacks/new
  def new
    @user_feedback = UserFeedback.new
  end

  # GET /user_feedbacks/1/edit
  def edit
  end

  # POST /user_feedbacks
  # POST /user_feedbacks.json
  def create
    @user_feedback = UserFeedback.new(user_feedback_params)

    respond_to do |format|
      if @user_feedback.save
        format.html { redirect_to @user_feedback, notice: 'User feedback was successfully created.' }
        format.json { render :show, status: :created, location: @user_feedback }
      else
        format.html { render :new }
        format.json { render json: @user_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_feedbacks/1
  # PATCH/PUT /user_feedbacks/1.json
  def update
    respond_to do |format|
      if @user_feedback.update(user_feedback_params)
        format.html { redirect_to @user_feedback, notice: 'User feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_feedback }
      else
        format.html { render :edit }
        format.json { render json: @user_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_feedbacks/1
  # DELETE /user_feedbacks/1.json
  def destroy
    @user_feedback.destroy
    respond_to do |format|
      format.html { redirect_to user_feedbacks_url, notice: 'User feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def last_feedback
    mobile_number = params[:mobile_number]
    mobile_numbers = UserFeedback.all.map{|m|m.mobile_number}
    if(mobile_numbers.include?mobile_number)
      user = UserFeedback.where(:mobile_number => mobile_number).last
      render :json => {:success=> true,:data => user.as_json(:only => [:current_brand,:current_variant, :other_brand, :other_variant,:no_of_sticks])}
      else
      render :json => {:success => false}
      end
  end
  
  def feedback
    puts params
    mobile_number = params[:mobile_number]
    current_brand = params[:current_brand]
    current_variant = params[:current_variant]
    other_brand = params[:other_brand]
    other_variant = params[:other_variant]
    no_of_sticks = params[:no_of_sticks]
    reason_cb = params[:reason_cb]
    reason_cv = params[:reason_cv]
    reason_ob = params[:reason_ob]
    reason_ov = params[:reason_ov]
    reason_sticks = params[:reason_sticks]
    UserFeedback.create!(:mobile_number => mobile_number,:current_brand => current_brand, :current_variant => current_variant, :other_brand => other_brand, :other_variant => other_variant, :no_of_sticks => no_of_sticks, :reason_cb => reason_cb, :reason_cv => reason_cv, :reason_ob => reason_ob, :reason_ov => reason_ov, :reason_sticks => reason_sticks)
    render :json => {:success => true}
  end
  
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_feedback
    @user_feedback = UserFeedback.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_feedback_params
    params.require(:user_feedback).permit(:mobile_number, :current_brand, :current_variant, :other_brand, :other_variant, :no_of_sticks, :reason_cb, :reason_cv, :reason_ob, :reason_ov, :reason_sticks)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_feedbacks_helper.rb
module UserFeedbacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TobaccoSurvey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_feedbacks/_form.html.erb
<%= form_for(@user_feedback) do |f| %>
  <% if @user_feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_feedback.errors.count, "error") %> prohibited this user_feedback from being saved:</h2>

      <ul>
      <% @user_feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mobile_number %><br>
    <%= f.text_field :mobile_number %>
  </div>
  <div class="field">
    <%= f.label :current_brand %><br>
    <%= f.text_field :current_brand %>
  </div>
  <div class="field">
    <%= f.label :current_variant %><br>
    <%= f.text_field :current_variant %>
  </div>
  <div class="field">
    <%= f.label :other_brand %><br>
    <%= f.text_field :other_brand %>
  </div>
  <div class="field">
    <%= f.label :other_variant %><br>
    <%= f.text_field :other_variant %>
  </div>
  <div class="field">
    <%= f.label :no_of_sticks %><br>
    <%= f.number_field :no_of_sticks %>
  </div>
  <div class="field">
    <%= f.label :reason_cb %><br>
    <%= f.text_field :reason_cb %>
  </div>
  <div class="field">
    <%= f.label :reason_cv %><br>
    <%= f.text_field :reason_cv %>
  </div>
  <div class="field">
    <%= f.label :reason_ob %><br>
    <%= f.text_field :reason_ob %>
  </div>
  <div class="field">
    <%= f.label :reason_ov %><br>
    <%= f.text_field :reason_ov %>
  </div>
  <div class="field">
    <%= f.label :reason_sticks %><br>
    <%= f.text_field :reason_sticks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_feedbacks/edit.html.erb
<h1>Editing User Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_feedback %> |
<%= link_to 'Back', user_feedbacks_path %>

app/views/user_feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Mobile number</th>
      <th>Current brand</th>
      <th>Current variant</th>
      <th>Other brand</th>
      <th>Other variant</th>
      <th>No of sticks</th>
      <th>Reason cb</th>
      <th>Reason cv</th>
      <th>Reason ob</th>
      <th>Reason ov</th>
      <th>Reason sticks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_feedbacks.each do |user_feedback| %>
      <tr>
        <td><%= user_feedback.mobile_number %></td>
        <td><%= user_feedback.current_brand %></td>
        <td><%= user_feedback.current_variant %></td>
        <td><%= user_feedback.other_brand %></td>
        <td><%= user_feedback.other_variant %></td>
        <td><%= user_feedback.no_of_sticks %></td>
        <td><%= user_feedback.reason_cb %></td>
        <td><%= user_feedback.reason_cv %></td>
        <td><%= user_feedback.reason_ob %></td>
        <td><%= user_feedback.reason_ov %></td>
        <td><%= user_feedback.reason_sticks %></td>
        <td><%= link_to 'Show', user_feedback %></td>
        <td><%= link_to 'Edit', edit_user_feedback_path(user_feedback) %></td>
        <td><%= link_to 'Destroy', user_feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User feedback', new_user_feedback_path %>

app/views/user_feedbacks/new.html.erb
<h1>New User Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', user_feedbacks_path %>

app/views/user_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mobile number:</strong>
  <%= @user_feedback.mobile_number %>
</p>

<p>
  <strong>Current brand:</strong>
  <%= @user_feedback.current_brand %>
</p>

<p>
  <strong>Current variant:</strong>
  <%= @user_feedback.current_variant %>
</p>

<p>
  <strong>Other brand:</strong>
  <%= @user_feedback.other_brand %>
</p>

<p>
  <strong>Other variant:</strong>
  <%= @user_feedback.other_variant %>
</p>

<p>
  <strong>No of sticks:</strong>
  <%= @user_feedback.no_of_sticks %>
</p>

<p>
  <strong>Reason cb:</strong>
  <%= @user_feedback.reason_cb %>
</p>

<p>
  <strong>Reason cv:</strong>
  <%= @user_feedback.reason_cv %>
</p>

<p>
  <strong>Reason ob:</strong>
  <%= @user_feedback.reason_ob %>
</p>

<p>
  <strong>Reason ov:</strong>
  <%= @user_feedback.reason_ov %>
</p>

<p>
  <strong>Reason sticks:</strong>
  <%= @user_feedback.reason_sticks %>
</p>

<%= link_to 'Edit', edit_user_feedback_path(@user_feedback) %> |
<%= link_to 'Back', user_feedbacks_path %>